[package]
name = "rust-actix-rentals"
version = "0.1.0"
authors = ["Esteban Borai <estebanborai@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "2"
actix-rt = "1"
dotenv = "0.11"
env_logger = "0.6"
log = "0.4"
serde = "1.0"
serde_json = "1.0"
