version: '3.4'

services:
  server:
    network_mode: host
    build:
      context: ./
      dockerfile: ./docker/server/Dockerfile

    ports:
      - "5000:5000"
    env_file:
      - .env

    environment:
      MODE: "${MODE}"
      HOST: "${HOST}"
      PORT: "${PORT}"
      RUST_LOG: "${RUST_LOG}"
      REDIS_HOST: "${REDIS_HOST}"
      REDIS_PORT: "${REDIS_PORT}"
      DATABASE_URL: "${DATABASE_URL}"

  database:
    build: ./docker/postgres
    ports:
      - "5432:5432"

  redis:
    build: ./docker/redis
    ports:
      - "6379:6379"
