
version: '3.4'

services:
  bmk_server:
    network_mode: host
    build:
      context: ./
      dockerfile: ./docker/server/Dockerfile
    ports:
      - "7878:7878"
    env_file:
      - .env
    environment:
      MODE: "${MODE}"
      HOST: "${HOST}"
      PORT: "${PORT}"
      SESSION_SECRET: "${SESSION_SECRET}"
      RUST_LOG: "${RUST_LOG}"
